# Initially snatched and adapted from libsodium .travis.yml

sudo: false

language:
- c

cache:
- ccache

os:
 - linux

compiler:
 - clang
 - gcc

before_script:
 - mkdir -p "${HOME}/tmp"

script:
 - ./configure --prefix "${HOME}/tmp" PKG_CONFIG_PATH="${HOME}/tmp/lib"
 - make all
 - make install
